name: calccombustivel
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_masked_text: ^0.8.0
  firebase_admob: ^0.10.2
  firebase_core: ^0.5.2+1
  flutter_native_admob: ^2.1.0+3


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/aog-white.png

  fonts:
    - family: Big Shoulders Display
      fonts:
        - asset: assets/fonts/BigShouldersDisplay-Light.ttf

